language: node_js
sudo: false
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY=AKIAJH2D5IPIRHYJT5IA
  - secure: "bHURxnyslyywLrdCs+xK4U/9A3x69e+M6Lpdv4joCutGGmq7uHaRMKLMcudB9mJ6yeJt7/c3U/qogqMZKtNtCM7xBTwPFQXLRedE4vyIYtqziSm17gOj43mAvPTpHGTI2vhtkZ8RNgRkJgve9yqbIUGLhHjIRsnuaVorzhs7Klq2h+q+PvHD6c5PBdOiLUhYPLOTkWp0deb8ZXuG1hFGq0aC8z1Y+zurC/Blc8rDzfLi6XZHMlTYkFHB0jZ5EW+hkPX9RcUMZ8SeAKXxmE4IBv25hxje84oDF8i+4Mi83t+GRZq58W+L5Nhq2I9lodagAcdPlMZ4tK8hNZh7B3YJ0JdoLl6TIp1xRKqpr3IVJPVlP2g/vv6PxqyHIsz3y1i5DU2ezbfJqw1nBHOjJjDAi1V4LzzdZNUfV9pvw0t56Yj+vVE2k/kxj7HGThBP514C+kLOw7XGPhxCip7UewNY+CiI0k9bEdglwtUwaL2euSDjb8vLhfkkW80A0VXk62p2pPC0EXlbqwQ9pflMyRCJPDZuv/h/BH4O4MsQMz3vfBjozsy/WtGiEf97dZJq4DiMR7Abp/OrDbvBcfz6CG3QWvM077XOiKYZFd+aflcGkQFeE2xUVOuOrvSFYwlPvttHrweLt+SUgq3cv77PHCmezL/SPrcasQUUQEpRKDulaVc="
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- "./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH"
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: C1W6eUXnanykbV5pJvAoOuVB0JYkW6cIvRlwShwV9ZBQopRQVWblppU913KvTn7vqoMnhaGJ+CXASr+KiF5O4sEaoQNhtqU3uB4suYRMvWn0OvH+PNXvvvLPQfCW0yPuyLPjuG71v/jeINDFUAA6Y3jFshxD5h/8/d21eMf/tok4kTQLVTbZx7UHjkYy3a+e0qYVkpsqStZBlnIQIV3ZifVjt7p/tWuk50oDhfJNw2Tl7Eb5I09tuocrmjoIcsGRHUzmj6I5/LjhZYQaLCPbn4kIiHv9nLRHXEkPulQixPmUY1s4NvsRTEd6pFUxuxAjbdKs5MCtWwDlUyUe8gkmMnWBoHrvROi7TE8bpIOzt9lEyrMJ3nUHyJgWISHrhUAZGbV6VexwEUKFYK1KgH3sdbZmDB0uhlRF/8usitH+r+6f1n5UQmnvqw818npaRDzw5gGjS9hESTqYduFTXrPYCj+Hvaa8WuoszMf//6FtSWv8lOYlcFtetZH7iNbZbRN9tD9gymRs1Yupvm+UXZUEOKMCBCbeOq4DA4G/rS5oo8VWB1GOuNAQoWUzdL3DsMMDm9APT2F9d8BHZzRCbAoF8c7ZcfdscR1CJEMzwcmeDSRNW9gIZNlvatnA7lBnR/0ICFjB/dlJtgSJGCTyziQcunLyTMd9IwJ9vBaAvl/IGuY=
  bucket: bluprinter.octoblu.com
  local_dir: dist
  region: us-west-2
  skip_cleanup: true
  endpoint: bluprinter.octoblu.com.s3-website-us-west-2.amazonaws.com
  detect_encoding: true
  on:
    tags: true
