language: node_js
sudo: false
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY=AKIAJH2D5IPIRHYJT5IA
  - secure: UCTLuA0kuf8kg1WBuQdiZQCWcGqt4iQ6/cG7TNv/PXVVtWysWukRj6j2NtDZ8g+aDIUNlry+0Gg49/F0hDJDMb72KrHWF96Me0IcSqpwgEs0Vv7k0fyvvn1Zfbkn2Svd7ZOG3o/cYdqq9OxkOtDQBbpd7mmhiyxUP/Fp7ojAki5PiGQhCPhXPhrsgchVTZ1sXdFNmOPALn1l3DrhbYHB3cmBj67pgzgl3SIVAE5Y8WDmxESZiWJQP01xJC0pgEdrJSJdswBGSMIRcYLcclUVA/Gy4YF/hGl2qzRE7M/uR627vrbSrhvFn6ixle4V1i2t23QOt9BOlxD0QRfFXlemGwpqFcIcUFCsoFxc5Xy7BC4Pmvz62/40/f8Y5dWghwPv0CccnKsnv/h/6GVWLSh2iaf/1gAmH26Iim0OiodJ+nU1kighRt+amgSSU1XHE9DYwRXDkH2EPLiWYouNdTsZKI/iMLkmjOydZABobrz+uRjQVhN0mlmo8lrzVVw75hIpousc0d4vd/RmP/Iulg6+FGiOZuIW0jesYigFQR73ooGG7FSaGuLJlxBwrdxBFyAV98rI0V3Xoh1Nf1/CKHb//KnakeCfpAGGWg3olibpcEk8WUdb7cQ1j2dzdETUOlyyT56FQef9Ib3TcfR/0vIW1liVJjyTZ3WoS1OUSkc1H8U=
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- ./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: C1W6eUXnanykbV5pJvAoOuVB0JYkW6cIvRlwShwV9ZBQopRQVWblppU913KvTn7vqoMnhaGJ+CXASr+KiF5O4sEaoQNhtqU3uB4suYRMvWn0OvH+PNXvvvLPQfCW0yPuyLPjuG71v/jeINDFUAA6Y3jFshxD5h/8/d21eMf/tok4kTQLVTbZx7UHjkYy3a+e0qYVkpsqStZBlnIQIV3ZifVjt7p/tWuk50oDhfJNw2Tl7Eb5I09tuocrmjoIcsGRHUzmj6I5/LjhZYQaLCPbn4kIiHv9nLRHXEkPulQixPmUY1s4NvsRTEd6pFUxuxAjbdKs5MCtWwDlUyUe8gkmMnWBoHrvROi7TE8bpIOzt9lEyrMJ3nUHyJgWISHrhUAZGbV6VexwEUKFYK1KgH3sdbZmDB0uhlRF/8usitH+r+6f1n5UQmnvqw818npaRDzw5gGjS9hESTqYduFTXrPYCj+Hvaa8WuoszMf//6FtSWv8lOYlcFtetZH7iNbZbRN9tD9gymRs1Yupvm+UXZUEOKMCBCbeOq4DA4G/rS5oo8VWB1GOuNAQoWUzdL3DsMMDm9APT2F9d8BHZzRCbAoF8c7ZcfdscR1CJEMzwcmeDSRNW9gIZNlvatnA7lBnR/0ICFjB/dlJtgSJGCTyziQcunLyTMd9IwJ9vBaAvl/IGuY=
  bucket: bluprinter.octoblu.com
  local_dir: dist
  region: us-west-2
  skip_cleanup: true
  endpoint: bluprinter.octoblu.com.s3-website-us-west-2.amazonaws.com
  detect_encoding: true
  on:
    tags: true
