language: node_js
sudo: false
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY=AKIAJH2D5IPIRHYJT5IA
  - secure: LIuqjEoIR/2HjOPpJrBlI6Vy7Ub18ADCymNIKqHP1SbYGGn73UsD0Z71VRmEYvRKk4gYXeFpuNzuGqC5Q7G9t4ZLw+wPlVY04xtYzXaA07QOXP2e9rrZ3P9ewtXe8jpAxqbQpOGLos3TML3dS6GnxemnN+U4dR58PYL78UxeI4lcylHtoLo4uemq57E9BgXelXQYYrUAE96diAbULI7YBz22bItQD/LxARWFaVE7ja5aJA5V9az67Q2/JjgwnlvxDof/+Td3fIsOMEzlmHc1uqFru5QK7NG3VUNCms9+B0MK4ftPCsiqSq9B0WJeo7Z7jU7zwTMZEoX4EFTOPoj4Qk3wDo6/0EP3nMI0/4RoqY+IH97i6bLC8oLEQfNEhS43tvlBInfH3DrFS1R92tBkGiClC813G+yJXbVCTA1p2iUEDpaVoaAvUWIqf7po5l2V1IhelRcrh4k10SiF+QcBjCWjacvXAS/6Q/top7v87TQrA/k+a7j0InMcFwJBNZDD73BTPGqL2nRx6skwW9lmhf4B71D4T7H26YPeFU+fRY1EPglQmuypJ/nYD1VSSkQlr5/Nbyr9AB/tWW8TNa03vLmzq5rIAajSiOpoGsyaEAiF67cNZQ3+5m20jPlH90PuKInSkuul3SU5TJ1DJfVsCoNUP9WjbGduezkicWuJmFE=
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- ./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: C1W6eUXnanykbV5pJvAoOuVB0JYkW6cIvRlwShwV9ZBQopRQVWblppU913KvTn7vqoMnhaGJ+CXASr+KiF5O4sEaoQNhtqU3uB4suYRMvWn0OvH+PNXvvvLPQfCW0yPuyLPjuG71v/jeINDFUAA6Y3jFshxD5h/8/d21eMf/tok4kTQLVTbZx7UHjkYy3a+e0qYVkpsqStZBlnIQIV3ZifVjt7p/tWuk50oDhfJNw2Tl7Eb5I09tuocrmjoIcsGRHUzmj6I5/LjhZYQaLCPbn4kIiHv9nLRHXEkPulQixPmUY1s4NvsRTEd6pFUxuxAjbdKs5MCtWwDlUyUe8gkmMnWBoHrvROi7TE8bpIOzt9lEyrMJ3nUHyJgWISHrhUAZGbV6VexwEUKFYK1KgH3sdbZmDB0uhlRF/8usitH+r+6f1n5UQmnvqw818npaRDzw5gGjS9hESTqYduFTXrPYCj+Hvaa8WuoszMf//6FtSWv8lOYlcFtetZH7iNbZbRN9tD9gymRs1Yupvm+UXZUEOKMCBCbeOq4DA4G/rS5oo8VWB1GOuNAQoWUzdL3DsMMDm9APT2F9d8BHZzRCbAoF8c7ZcfdscR1CJEMzwcmeDSRNW9gIZNlvatnA7lBnR/0ICFjB/dlJtgSJGCTyziQcunLyTMd9IwJ9vBaAvl/IGuY=
  bucket: bluprinter.octoblu.com
  local_dir: dist
  region: us-west-2
  skip_cleanup: true
  endpoint: bluprinter.octoblu.com.s3-website-us-west-2.amazonaws.com
  detect_encoding: true
  on:
    tags: true
