language: node_js
sudo: false
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - secure: HcqyEz08c6XKuEkTQsORz4UbBOmA+evPSFRnHwzNfPb+sAf7mtwqyWTOufxAX+ivIX4B/nQob5cxxJ3eveDdpHTKgUHoIGs3NV3+H37SrXfyqIkc0iXZRrNyWPFT62CTZsp96yRdZakEYFynltTfvlkR2+KN8Mdc7viDsTp/HS/vA56eXZWhfnKi/Yx7vUoDA4vWV1QJiNKu4mAI+xAkn08B1w0r4IUAkgc8wIJgyOgkXZ7om2UdN1nUko/lvx/5UJnc/Os8ynr++MVuqwA0NtejiOcUpZ59QYaZ/1CABuxoadGRKnw2KERHf+ODuQqcT2MnhTN6wIP7S1D5MsObbKBTEr0/++a5vy6NS2+8DFQXqGNFOJWkOWn4cuUvHcJiiSNNlxJW4Gb8vsJYRndjZju9nMKVIPaAlzuQWXmDHioWEw68coGI+R2yxFjk4tZP/s5HKjK/ynqIkLzT/v3EzaP0UrRj5J5cKKzfIArfbxDetZbHSHbc5Rvompv0zML7E+NUcBEWnd/fLbYxgcrP5dSSFNK4FPrREbw2E9z6Zzw68Nz7P1wzOim/6P/jDrsvPpiP3pVKFtPDUAmTr1WETuKWgIRF0lHpZ4jPXXjZD/AfnoXdJpRd7pyD28RQcvxuAHAzR9kz3MXaXOQxyeKN3KhGbl6uPUd1w3SLJ96zWT8=
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- ./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: C1W6eUXnanykbV5pJvAoOuVB0JYkW6cIvRlwShwV9ZBQopRQVWblppU913KvTn7vqoMnhaGJ+CXASr+KiF5O4sEaoQNhtqU3uB4suYRMvWn0OvH+PNXvvvLPQfCW0yPuyLPjuG71v/jeINDFUAA6Y3jFshxD5h/8/d21eMf/tok4kTQLVTbZx7UHjkYy3a+e0qYVkpsqStZBlnIQIV3ZifVjt7p/tWuk50oDhfJNw2Tl7Eb5I09tuocrmjoIcsGRHUzmj6I5/LjhZYQaLCPbn4kIiHv9nLRHXEkPulQixPmUY1s4NvsRTEd6pFUxuxAjbdKs5MCtWwDlUyUe8gkmMnWBoHrvROi7TE8bpIOzt9lEyrMJ3nUHyJgWISHrhUAZGbV6VexwEUKFYK1KgH3sdbZmDB0uhlRF/8usitH+r+6f1n5UQmnvqw818npaRDzw5gGjS9hESTqYduFTXrPYCj+Hvaa8WuoszMf//6FtSWv8lOYlcFtetZH7iNbZbRN9tD9gymRs1Yupvm+UXZUEOKMCBCbeOq4DA4G/rS5oo8VWB1GOuNAQoWUzdL3DsMMDm9APT2F9d8BHZzRCbAoF8c7ZcfdscR1CJEMzwcmeDSRNW9gIZNlvatnA7lBnR/0ICFjB/dlJtgSJGCTyziQcunLyTMd9IwJ9vBaAvl/IGuY=
  bucket: bluprinter.octoblu.com
  local_dir: dist
  region: us-west-2
  skip_cleanup: true
  endpoint: bluprinter.octoblu.com.s3-website-us-west-2.amazonaws.com
  detect_encoding: true
  on:
    tags: true
