language: node_js
sudo: false
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY=AKIAJH2D5IPIRHYJT5IA
  - secure: F/Kx5lPmYoUKtUkISaGL6UlLHXq6Z3pLYEZT2QETnzBVTIJRZ1Sra42JqeALJGf2hiyj/V9HZtybXaphOui/djvQuTrdGKNN6kDR4a+mxHNe6++pvUbrzEmOU7l0CAZhN0q3nNtlc6E5Otd0mqgrnZ8/tDE66q9lJIMih+CUF1899dPTJo8x4LhgSoULAnfD+d9Gy2jYrPGFD3joOpi/M1vNu5fIJHo/wbH/FTEBsF7GnPNjb26OwhZfO0aJAmc5Dig0Htu7z+B9pT4Iz/QNtm7qY7fIiNlnwJFijwr6bThInwrCfo/kTzs6KIp6mESBthwRJFxLGLBG88xJtJv1HV1nCxVj3VkfOhE4bgBv2TF/3BQvhTVoEswxnbNgdQNwWTWAakQVnWSkHujNXT0fkDCFE4p5oBDKT9e7uaRKwBNu8+C4U6sUfh2Ipcw4U/ZHqh+02O46FZxbtkyeuzqRnuK7O7w6czdLJGJ6H5cwjKAIkr4uqcpSxQDi9Sf0PAYtZBlTQ7PCnKoImbkvx3Czpxw8afW1cBBt8zVXGvNGSGqUltL8NUckNgGE5TuCccwTUNwlsfjjLkOZuS+j/vHZbYIKy9ClaJ7t5vKqccHo01GCNcMhaIf4Qt12yZc1Hv2TLNr/AdfRvCNBeBuugBrXIWjj9tBYk2OpZIAq6hKhz0U=
before_deploy:
- npm run build
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: C1W6eUXnanykbV5pJvAoOuVB0JYkW6cIvRlwShwV9ZBQopRQVWblppU913KvTn7vqoMnhaGJ+CXASr+KiF5O4sEaoQNhtqU3uB4suYRMvWn0OvH+PNXvvvLPQfCW0yPuyLPjuG71v/jeINDFUAA6Y3jFshxD5h/8/d21eMf/tok4kTQLVTbZx7UHjkYy3a+e0qYVkpsqStZBlnIQIV3ZifVjt7p/tWuk50oDhfJNw2Tl7Eb5I09tuocrmjoIcsGRHUzmj6I5/LjhZYQaLCPbn4kIiHv9nLRHXEkPulQixPmUY1s4NvsRTEd6pFUxuxAjbdKs5MCtWwDlUyUe8gkmMnWBoHrvROi7TE8bpIOzt9lEyrMJ3nUHyJgWISHrhUAZGbV6VexwEUKFYK1KgH3sdbZmDB0uhlRF/8usitH+r+6f1n5UQmnvqw818npaRDzw5gGjS9hESTqYduFTXrPYCj+Hvaa8WuoszMf//6FtSWv8lOYlcFtetZH7iNbZbRN9tD9gymRs1Yupvm+UXZUEOKMCBCbeOq4DA4G/rS5oo8VWB1GOuNAQoWUzdL3DsMMDm9APT2F9d8BHZzRCbAoF8c7ZcfdscR1CJEMzwcmeDSRNW9gIZNlvatnA7lBnR/0ICFjB/dlJtgSJGCTyziQcunLyTMd9IwJ9vBaAvl/IGuY=
  bucket: bluprinter.octoblu.com
  region: 'us-west-2'
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: octoblu/bluprinter
    tags: true
after_deploy:
- "./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH"
- cp index.html dist
