export const CREATE_BLUPRINT         = 'CREATE_BLUPRINT'
export const CREATE_BLUPRINT_REQUEST = 'CREATE_BLUPRINT_REQUEST'
export const CREATE_BLUPRINT_SUCCESS = 'CREATE_BLUPRINT_SUCCESS'
export const CREATE_BLUPRINT_FAILURE = 'CREATE_BLUPRINT_FAILURE'


export const GET_FLOW         = 'GET_FLOW'
export const GET_FLOW_REQUEST = 'GET_FLOW_REQUEST'
export const GET_FLOW_SUCCESS = 'GET_FLOW_SUCCESS'
export const GET_FLOW_FAILURE = 'GET_FLOW_FAILURE'
