export const CREATE_BLUPRINT         = 'CREATE_BLUPRINT'
export const CREATE_BLUPRINT_REQUEST = 'CREATE_BLUPRINT_REQUEST'
export const CREATE_BLUPRINT_SUCCESS = 'CREATE_BLUPRINT_SUCCESS'
export const CREATE_BLUPRINT_FAILURE = 'CREATE_BLUPRINT_FAILURE'

export const GET_BLUPRINT         = 'GET_BLUPRINT'
export const GET_BLUPRINT_REQUEST = 'GET_BLUPRINT_REQUEST'
export const GET_BLUPRINT_SUCCESS = 'GET_BLUPRINT_SUCCESS'
export const GET_BLUPRINT_FAILURE = 'GET_BLUPRINT_FAILURE'

export const SET_BLUPRINT_MANIFEST         = 'SET_BLUPRINT_MANIFEST'
export const SET_BLUPRINT_MANIFEST_REQUEST = 'SET_BLUPRINT_MANIFEST_REQUEST'
export const SET_BLUPRINT_MANIFEST_SUCCESS = 'SET_BLUPRINT_MANIFEST_SUCCESS'
export const SET_BLUPRINT_MANIFEST_FAILURE = 'SET_BLUPRINT_MANIFEST_FAILURE'

export const UPDATE_BLUPRINT         = 'UPDATE_BLUPRINT'
export const UPDATE_BLUPRINT_REQUEST = 'UPDATE_BLUPRINT_REQUEST'
export const UPDATE_BLUPRINT_SUCCESS = 'UPDATE_BLUPRINT_SUCCESS'
export const UPDATE_BLUPRINT_FAILURE = 'UPDATE_BLUPRINT_FAILURE'

export const GET_FLOW         = 'GET_FLOW'
export const GET_FLOW_REQUEST = 'GET_FLOW_REQUEST'
export const GET_FLOW_SUCCESS = 'GET_FLOW_SUCCESS'
export const GET_FLOW_FAILURE = 'GET_FLOW_FAILURE'

export const DEPLOY_BLUPRINT         = 'DEPLOY_BLUPRINT'
export const DEPLOY_BLUPRINT_REQUEST = 'DEPLOY_BLUPRINT_REQUEST'
export const DEPLOY_BLUPRINT_SUCCESS = 'DEPLOY_BLUPRINT_SUCCESS'
export const DEPLOY_BLUPRINT_FAILURE = 'DEPLOY_BLUPRINT_FAILURE'

export const MAKE_FLOW_DISCOVERABLE         = 'MAKE_FLOW_DISCOVERABLE'
export const MAKE_FLOW_DISCOVERABLE_REQUEST = 'MAKE_FLOW_DISCOVERABLE_REQUEST'
export const MAKE_FLOW_DISCOVERABLE_SUCCESS = 'MAKE_FLOW_DISCOVERABLE_SUCCESS'
export const MAKE_FLOW_DISCOVERABLE_FAILURE = 'MAKE_FLOW_DISCOVERABLE_FAILURE'

export const UPDATE_SHARED_DEVICES_PERMISSIONS         = 'UPDATE_SHARED_DEVICES_PERMISSIONS'
export const UPDATE_SHARED_DEVICES_PERMISSIONS_REQUEST = 'UPDATE_SHARED_DEVICES_PERMISSIONS_REQUEST'
export const UPDATE_SHARED_DEVICES_PERMISSIONS_SUCCESS = 'UPDATE_SHARED_DEVICES_PERMISSIONS_SUCCESS'
export const UPDATE_SHARED_DEVICES_PERMISSIONS_FAILURE = 'UPDATE_SHARED_DEVICES_PERMISSIONS_FAILURE'

export const GET_OPERATION_SCHEMAS         = 'GET_OPERATION_SCHEMAS'
export const GET_OPERATION_SCHEMAS_REQUEST = 'GET_OPERATION_SCHEMAS_REQUEST'
export const GET_OPERATION_SCHEMAS_SUCCESS = 'GET_OPERATION_SCHEMAS_SUCCESS'
export const GET_OPERATION_SCHEMAS_FAILURE = 'GET_OPERATION_SCHEMAS_FAILURE'

export const SET_DEVICE_SCHEMAS         = 'SET_DEVICE_SCHEMAS'
export const SET_DEVICE_SCHEMAS_REQUEST = 'SET_DEVICE_SCHEMAS_REQUEST'
export const SET_DEVICE_SCHEMAS_SUCCESS = 'SET_DEVICE_SCHEMAS_SUCCESS'
export const SET_DEVICE_SCHEMAS_FAILURE = 'SET_DEVICE_SCHEMAS_FAILURE'

export const SET_BLUPRINT_CONFIG_SCHEMA  = 'SET_BLUPRINT_CONFIG_SCHEMA'
export const SET_BLUPRINT_SHARED_DEVICES = 'SET_BLUPRINT_SHARED_DEVICES'
export const SET_MESSAGE_SCHEMA          = 'SET_MESSAGE_SCHEMA'
export const SET_OCTOBLU_LINKS           = 'SET_OCTOBLU_LINKS'

export const GET_BLUPRINTS         = 'GET_BLUPRINTS'
export const GET_BLUPRINTS_REQUEST = 'GET_BLUPRINTS_REQUEST'
export const GET_BLUPRINTS_SUCCESS = 'GET_BLUPRINTS_SUCCESS'
export const GET_BLUPRINTS_FAILURE = 'GET_BLUPRINTS_FAILURE'
