export const MESHBLU_HOST              = 'meshblu.octoblu.dev'
export const OAUTH_CLIENT_ID           = '12293e51-9122-4402-9063-6d3a41a8507f'
export const OAUTH_PROVIDER_URI        = 'https://oauth.octoblu.dev'
export const OCTOBLU_URL               = 'https://app.octoblu.dev'
export const BLUPRINTER_URL            = 'https://bluprinter.octoblu.dev'
export const FLOW_DEPLOY_URL           = 'https://nanocyte-flow-deploy.octoblu.dev'
export const TOOLS_SCHEMA_REGISTRY_URL = 'https://s3-us-west-2.amazonaws.com/tool-schema-registry/latest/schema-registry.json'
export const NODE_SERVICE_URL          = 'https://nanocyte-flow-deploy.octoblu.dev'
