exports.MESHBLU_HOST              = 'meshblu.octoblu.com'
exports.OAUTH_CLIENT_ID           = '12293e51-9122-4402-9063-6d3a41a8507f'
exports.OAUTH_PROVIDER_URI        = 'https://oauth.octoblu.com'
exports.OCTOBLU_URL               = 'https://app.octoblu.com'
exports.FLOW_DEPLOY_URL           = 'https://nanocyte-flow-deploy.octoblu.com'
exports.TOOLS_SCHEMA_REGISTRY_URL = 'https://s3-us-west-2.amazonaws.com/tool-schema-registry/latest/schema-registry.json'
