exports.MESHBLU_HOST              = 'meshblu.octoblu.com'
exports.OAUTH_CLIENT_ID           = '1addf5c8-4d4e-498b-832f-74995978f115'
exports.OAUTH_PROVIDER_URI        = 'https://oauth.octoblu.com'
exports.OCTOBLU_URL               = 'https://app.octoblu.com'
exports.FLOW_DEPLOY_URL           = 'https://nanocyte-flow-deploy.octoblu.com'
exports.TOOLS_SCHEMA_REGISTRY_URL = 'https://s3-us-west-2.amazonaws.com/tool-schema-registry/latest/schema-registry.json'
